# Generated by Django 5.2.10 on 2026-02-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("image_url", models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name="category",
            name="image_url",
            field=models.URLField(blank=True),
        ),
    ]
