# Generated by Django 5.2.10 on 2026-02-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_banner_category_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="image_url",
            field=models.ImageField(upload_to="banners/"),
        ),
        migrations.AlterField(
            model_name="category",
            name="image_url",
            field=models.ImageField(blank=True, upload_to="categories/"),
        ),
        migrations.AlterField(
            model_name="productmedia",
            name="file_url",
            field=models.ImageField(upload_to="products/"),
        ),
    ]
