services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
      args:
        NGINX_CONF: ${NGINX_CONF:-prod.conf}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_data:/static:ro
      - media_data:/media:ro
      - letsencrypt:/etc/letsencrypt
      - certbot_www:/var/www/certbot

  certbot:
    image: certbot/certbot:latest
    volumes:
      - letsencrypt:/etc/letsencrypt
      - certbot_www:/var/www/certbot

  # redis:
  #   image: redis:7-alpine
  #   restart: unless-stopped

  # celeryworker:
  #   build: ./backend
  #   command: celery -A config worker -l info
  #   env_file:
  #     - ./backend/.env
  #   depends_on:
  #     redis:
  #       condition: service_started

  # celerybeat:
  #   build: ./backend
  #   command: celery -A config beat -l info
  #   env_file:
  #     - ./backend/.env
  #   depends_on:
  #     redis:
  #       condition: service_started

volumes:
  letsencrypt:
  certbot_www:
