# Generated by Django 5.2.10 on 2026-03-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[("not_paid", "Not paid"), ("paid", "Paid")],
                default="not_paid",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_work", "In work"),
                    ("assembly", "Assembly"),
                    ("shipping", "Shipping"),
                    ("complete", "Complete"),
                ],
                default="in_work",
                max_length=20,
            ),
        ),
    ]
