# Generated by ChatGPT on 2025-02-14
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "carrier",
                    models.CharField(
                        choices=[
                            ("cdek", "CDEK"),
                            ("pickup", "Pickup"),
                            ("custom", "Custom"),
                        ],
                        default="cdek",
                        max_length=20,
                    ),
                ),
                ("service_code", models.CharField(blank=True, max_length=50)),
                ("tracking_number", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("in_transit", "In transit"),
                            ("delivered", "Delivered"),
                            ("canceled", "Canceled"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("cost", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("label_url", models.URLField(blank=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipment",
                        to="orders.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShipmentAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient_name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=50)),
                ("address_line1", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                ("country", models.CharField(default="RU", max_length=50)),
                ("delivery_type", models.CharField(default="courier", max_length=20)),
                ("pickup_point_code", models.CharField(blank=True, max_length=50)),
                (
                    "shipment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address",
                        to="shipping.shipment",
                    ),
                ),
            ],
        ),
    ]
